baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jose Garcia | Scientific Developer'

[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'

[params]
  dateFormat = 'Jan 02, 2006'
  dateFormatMicroblog = 'January 02, 2006'
  title = "Hi! I'm Jose."
  description = "I'm civil Engineer leading multidisciplinary projects in water resources management and hydraulic engineering, with focus on developing innovative solutions through computational modeling and data analysis."
  head_image = "/images/jose-garcia-head.jpeg"

[taxonomies]
  category = "categories"
  author = "authors"

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Microposts'
    pageRef = '/microposts'
    weight = 20
  [[menus.main]]
    name = 'Archive'
    pageRef = '/archive'
    weight = 30
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[related]
  includeNewer = false
  threshold = 80
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100
    
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'